config/routes.rb
Rails.application.routes.draw do
  get 'client_panel/index'

  devise_for :clients, controllers: { registrations: "clients/registrations"}
  resources :clients
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users

  get 'packages/index'

  get 'packages/new'

  get 'packages/create'

  get 'packages/edit'

  get 'packages/update'

  get 'packages/show'

  get 'packages/destroy'

  get 'orders/index'

  get 'orders/new'

  get 'orders/create'

  get 'orders/edit'

  get 'orders/update'

  get 'orders/show'

  get 'orders/destroy'

  get 'couriers/index'

  get 'couriers/new'

  get 'couriers/create'

  get 'couriers/edit'

  get 'couriers/update'

  get 'couriers/show'

  get 'couriers/destroy'

  get 'dispathers_office/index'

  get 'dispathers_office/new'

  get 'dispathers_office/create'

  get 'dispathers_office/edit'

  get 'dispathers_office/update'

  get 'dispathers_office/show'

  get 'dispathers_office/destroy'

  get 'warehouses/index'

  get 'warehouses/new'

  get 'warehouses/create'

  get 'warehouses/edit'

  get 'warehouses/update'

  get 'warehouses/show'

  get 'warehouses/destory'

  get 'user/index'

  match ':controller(/:action(/:id))', :via => [:get, :post]

  root 'home#index'

end

app/controllers/client_panel_controller.rb
class ClientPanelController < ApplicationController
  def index
    @orders = Order.all
    @packages = Package.all
  end
end

app/helpers/client_panel_helper.rb
module ClientPanelHelper
end

app/views/client_panel/index.html.erb
        <div class="wrapper-login">
            <div class="container">
                <div class="row">
                    <div class=" col-xs-12 text-center">
                        <h3>Panel klienta</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="content-main col-xs-12">
                        <div class="options no-padding">
                            <% if client_signed_in? %>
                              <div class="row">
                                <ul class="panel-option col-xs-12">
                                  <li class="panel-option-single col-xs-3">
                                      <a href="/">
                                          <div class="inner">
                                              <i class="fa fa-home" aria-hidden="true"></i>
                                              Strona główna
                                          </div>
                                      </a>
                                  </li>
                                  <li class="panel-option-single col-xs-3">
                                    <a href="/orders/new">
                                      <div class="inner">
                                          <i class="fa fa-archive" aria-hidden="true"></i>
                                          Nadaj paczkę
                                      </div>
                                    </a>
                                  </li>
                                  <li class="panel-option-single col-xs-3">
                                    <a href="/clients/edit">
                                        <div class="inner">
                                            <i class="fa fa-user" aria-hidden="true"></i>
                                            Edytuj dane
                                        </div>
                                      </a>
                                  </li>
                                  <li class="panel-option-single col-xs-3">
                                    <a href="/clients/sign_out">
                                      <div class="inner">
                                          <i class="fa fa-sign-out" aria-hidden="true"></i>
                                          Wyloguj się
                                      </div>
                                    </a>
                                  </li>
                              </ul>
                            </div>
                            <div class="row">
                              <div class="col-xs-12">
                                <h5>Moje Paczki</h5>
                                <%= link_to("Nadaj paczke", {:controller => 'orders', :action => 'new'}, :class=>"btn btn-raised btn-success btn-sm")%>
                                  <table class="table table-striped table-hover" style="margin-top: 20px; ">
                                      <tr style="color: black;">
                                        <th class="text-center">Numer zamówienia</th>
                                        <th class="text-center">Status</th>
                                      </tr>
                                      <% @orders.each do |order| %>
                                        <% if order.client_id == current_client.id %>
                                        <tr>
                                         <td><%=order.order_number %></td>
                                         <td><%=order.status%></td>
                                        </tr>
                                        <% end %>
                                    <% end %>
                                  </table>
                              </div>
                            </div>
                            <% else %>
                              <h1>Nie jesteś zalogowany</h1>
                              <%= link_to "Zarejestruj się", new_client_registration_path %> lub <%= link_to "Zaloguj się", new_client_session_path %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>